### ISSUE TITLE
urllib3 errors

### ISSUE THREAD

**Issue by doctorcolossus** [sshh12/Tradinhood#3]
Today I have gotten two different errors from urllib3 through Tradinhood.
The first is "Connection aborted, Remote end closed connection without response" while querying account_info on line 452 of Robinhood.py.
The second is "Connection aborted, OSError(22, 'Invalid argument'))" when querying current_quote from line 566 of Robinhood.py.
In both cases I would expect Tradinhood to gracefully handle the errors without unexpectedly terminating.
Please let me know if you would like me to open a second issue to separate the two errors, or in case there is any further information I can provide. Thank you.

I believe I was running on commit 708c68b3cbd09d9bb1a99291044bbc19198b8499 when I got the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Tradinhood/Tradinhood/Robinhood.py", line 448, in account_info
    res = self.session.get(ENDPOINTS['accounts'] + self.acc_num)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./tradinhood.py", line 235, in <module>
    wealth_now = wealth()
  File "./tradinhood.py", line 114, in wealth
    return buy_power() + stock_value() + crypto_value(data) + dollars_pending()
  File "./tradinhood.py", line 117, in buy_power
    return Decimal(rbh.account_info['margin_balances']['overnight_buying_power'])
  File "~/Tradinhood/Tradinhood/Robinhood.py", line 452, in account_info
    raise APIError('Unable to access account')
Tradinhood.Robinhood.APIError: Unable to access account
```
After that I pulled the latest (0698a93725c4ac0bb7a9ab21dc7b98b55cee883d) and got the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/Tradinhood/Tradinhood/Robinhood.py", line 562, in current_quote
    res = self.session.get(ENDPOINTS['forex_market_quote'] + self.pair_id + '/')
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(22, 'Invalid argument'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tradinhood.py", line 212, in <module>
    symbol_stats['price'] = rbh[symbol].price.normalize()
  File "~/Tradinhood/Tradinhood/Robinhood.py", line 571, in price
    return Decimal(self.current_quote['mark_price'])
  File "~/Tradinhood/Tradinhood/Robinhood.py", line 566, in current_quote
    raise APIError('Unable to access currency data')
Tradinhood.Robinhood.APIError: Unable to access currency data
```

**Comment by doctorcolossus** [comment]
By the way, to avoid any possible confusion, please note that my program which uses your library is called "tradinhood.py" (lower-case T). ;) I ought to choose a more creative name for it...

**Comment by sshh12** [comment]
It looks like in both cases something when wrong when calling the Robinhood servers.

Throwing an error (specifically a `Robinhood.APIError`) when something goes wrong contacting an endpoint is the expected behavior.

What you can do is simply wrap your error-throwing code with a try catch, ex:
```python
try: 
    money = rbh.buying_power
except Robinhood.APIError:
    money = 0
```

**Comment by sshh12** [comment]
If something known is systematically causing these requests to fail (login timeout, remote account change, etc), let me know and ill see what I can do to mitigate the issue.

**Comment by doctorcolossus** [comment]
Okay, that makes sense.
Thanks for your suggestion.
I'll report back if and when I find out more about what causes these issues.
